FROM golang:alpine AS builder
WORKDIR /build/
COPY go.mod go.sum ./
RUN go mod tidy
COPY main.go ./
RUN go build -o app

FROM alpine:latest  
WORKDIR /root/
COPY web/ ./web/
COPY cache/ ./cache/
COPY --from=builder /build/app ./
ENTRYPOINT ./app
EXPOSE 3000